"""
Seed data – realistic French hardware store product catalogue.
Used:
  • as fallback when live scraping is blocked
  • for local development and CI testing
  • to pre-populate the vector index on first run

Covers four categories matching the assignment:
  Plomberie | Électricité | Carrelage | Menuiserie
"""

from __future__ import annotations
import uuid
from datetime import datetime

_TS = datetime.utcnow().isoformat()


def _p(name, category, price, unit="unit", description=None, subcategory=None):
    return {
        "id": str(uuid.uuid4()),
        "name": name,
        "category": category,
        "subcategory": subcategory,
        "description": description or name,
        "price": price,
        "currency": "EUR",
        "unit": unit,
        "reference": None,
        "url": None,
        "source": "seed_data",
        "scraped_at": _TS,
    }


def get_seed_products() -> list[dict]:
    return [
        # ── Plomberie ────────────────────────────────────────────────────────
        _p("Chauffe-eau électrique vertical 200L - Thermor", "Plomberie", 459.00,
           description="Chauffe-eau électrique vertical 200 litres, résistance blindée, classe énergétique C",
           subcategory="Chauffe-eau"),
        _p("Chauffe-eau électrique vertical 150L - Atlantic", "Plomberie", 329.00,
           description="Chauffe-eau Atlantic 150L vertical, résistance stéatite, garantie 5 ans",
           subcategory="Chauffe-eau"),
        _p("Chauffe-eau électrique 100L compact - Ariston", "Plomberie", 249.00,
           description="Chauffe-eau compact 100 litres, installation murale, thermostat réglable",
           subcategory="Chauffe-eau"),
        _p("Chauffe-eau électrique 300L - Thermor Prodigy", "Plomberie", 649.00,
           description="Ballon d'eau chaude 300L, grande capacité, idéal famille nombreuse",
           subcategory="Chauffe-eau"),
        _p("Kit de raccordement chauffe-eau flexible 20x27", "Plomberie", 15.90,
           description="Kit flexible double pour raccordement chauffe-eau, 2 flexibles inox + joint",
           subcategory="Raccordement"),
        _p("Kit de raccordement chauffe-eau groupe sécurité", "Plomberie", 22.50,
           description="Groupe de sécurité + robinet d'arrêt + flexible pour cumulus",
           subcategory="Raccordement"),
        _p("Groupe de sécurité 3/4 pour chauffe-eau", "Plomberie", 18.90,
           description="Groupe de sécurité 20/27 avec clapet anti-retour, pression max 8 bars",
           subcategory="Raccordement"),
        _p("Tuyau multicouche PER 16mm - rouleau 25m", "Plomberie", 34.90,
           "rouleau",
           description="Tuyau multi-couche pour eau chaude et froide, gaine rouge/bleue incluse"),
        _p("Tuyau PVC évacuation 100mm - barre 2m", "Plomberie", 12.50,
           "barre",
           description="Tube PVC NFE pour évacuation eaux usées, diamètre 100mm"),
        _p("Coude 90° PVC 40mm femelle-femelle", "Plomberie", 1.80,
           description="Raccord coude 90° pour tuyauterie PVC, diam 40mm"),
        _p("Robinet vanne quart de tour 15/21", "Plomberie", 8.90,
           description="Robinet d'arrêt laiton 1/4 de tour, 15x21mm"),
        _p("Receveur de douche extra-plat 120x80 blanc", "Plomberie", 189.00,
           description="Receveur de douche acrylique extra-plat, 120x80cm, évacuation centré"),
        _p("Receveur de douche extra-plat 80x80 ardoise", "Plomberie", 149.00,
           description="Receveur de douche 80x80 texture ardoise, anti-dérapant"),
        _p("Colonne de douche thermostatique inox", "Plomberie", 249.00,
           description="Colonne de douche avec mitigeur thermostatique, douchette et doucherain"),
        _p("Bonde de douche extra-plate inox DN50", "Plomberie", 35.90,
           description="Bonde évacuation extra-plate pour receveur, grille inox brossé"),
        _p("Robinet mitigeur lavabo chromé", "Plomberie", 79.90,
           description="Mitigeur lavabo chromé, bec standard, flexibles d'alimentation inclus"),
        _p("Siphon de lavabo en PVC avec bouchon", "Plomberie", 7.50,
           description="Siphon tubulaire réglable pour lavabo, sortie horizontale ou verticale"),
        _p("Tube cuivre 12/14 - barre 1m", "Plomberie", 6.80, "barre",
           description="Tube cuivre écroui pour installations sanitaires et chauffage"),
        _p("Colle PVC pression 125ml", "Plomberie", 8.90,
           description="Colle solvantante pour assemblage tubes PVC pression, teinte grise"),
        _p("Teflon ruban PTFE 12mm x 12m", "Plomberie", 2.10,
           description="Ruban d'étanchéité PTFE pour raccords filetés"),

        # ── Électricité ──────────────────────────────────────────────────────
        _p("Câble électrique H07VU 2.5mm² rouge - rouleau 10m", "Électricité", 9.90,
           "rouleau", description="Fil électrique rigide 2.5mm² pour circuits prises",
           subcategory="Câbles"),
        _p("Câble électrique H07VU 1.5mm² blanc - rouleau 10m", "Électricité", 7.50,
           "rouleau", description="Fil rigide 1.5mm² pour circuits éclairage",
           subcategory="Câbles"),
        _p("Câble souple H05VV-F 3G1.5 - rouleau 10m", "Électricité", 11.90,
           "rouleau", description="Câble souple 3 fils 1.5mm² pour appareils électroménagers",
           subcategory="Câbles"),
        _p("Câble U1000R2V 3G2.5 - rouleau 25m", "Électricité", 49.90,
           "rouleau", description="Câble d'alimentation enterrable 3G2.5mm², gaine PVC noir",
           subcategory="Câbles"),
        _p("Disjoncteur 20A phase + neutre Legrand", "Électricité", 18.90,
           description="Disjoncteur modulaire 20A 2P pour tableau électrique, pouvoir de coupure 6kA",
           subcategory="Tableau électrique"),
        _p("Disjoncteur 16A 1P+N Schneider", "Électricité", 14.50,
           description="Disjoncteur 16A monophasé pour protection circuit éclairage",
           subcategory="Tableau électrique"),
        _p("Interrupteur différentiel 40A 30mA type A", "Électricité", 45.90,
           description="ID 40A 30mA type A pour protection circuits avec électronique",
           subcategory="Tableau électrique"),
        _p("Prise de courant 2P+T 16A blanc Legrand", "Électricité", 5.90,
           description="Prise murale 2 pôles + terre 16A, finition blanc",
           subcategory="Appareillage"),
        _p("Interrupteur va-et-vient 10A blanc", "Électricité", 4.90,
           description="Interrupteur va-et-vient 10A 250V, encastrable, blanc",
           subcategory="Appareillage"),
        _p("Boîte d'encastrement ø67mm profondeur 40mm", "Électricité", 0.90,
           description="Boîte d'encastrement pour appareillage, polypropylène",
           subcategory="Boîtes"),
        _p("Goulotte électrique PVC 50x50mm barre 2m", "Électricité", 12.90,
           "barre", description="Goulotte de câblage PVC blanc avec couvercle clipsable",
           subcategory="Goulottes"),
        _p("Spot LED encastrable 6W - blanc chaud", "Électricité", 12.90,
           description="Spot LED 6W GU10 blanc chaud 3000K, trou de perçage 70mm",
           subcategory="Éclairage"),
        _p("Luminaire plafonnier LED 24W rond", "Électricité", 29.90,
           description="Plafonnier LED 24W, lumière blanche naturelle 4000K, IP44",
           subcategory="Éclairage"),
        _p("Tableau électrique nu 13 modules", "Électricité", 24.90,
           description="Coffret électrique encastrable 13 modules, plastique, avec porte",
           subcategory="Tableau électrique"),
        _p("Gaine ICTA 20mm - rouleau 25m", "Électricité", 8.50,
           "rouleau", description="Gaine ICTA souple ø20mm pour passage de câbles sous enduit",
           subcategory="Câbles"),
        _p("Domino de connexion 10mm² (sachet 5)", "Électricité", 3.20,
           "sachet", description="Borniers de connexion universels 10mm² bipolaires",
           subcategory="Raccordement"),

        # ── Carrelage ────────────────────────────────────────────────────────
        _p("Carrelage sol grès cérame gris 60x60 - m²", "Carrelage", 22.90,
           "m2", description="Carrelage sol intérieur grès cérame gris anthracite 60x60cm, R9",
           subcategory="Carrelage sol"),
        _p("Carrelage sol gris clair 60x60 effet béton - m²", "Carrelage", 19.90,
           "m2", description="Carrelage sol grès cérame rectifié 60x60 effet béton, finition mate",
           subcategory="Carrelage sol"),
        _p("Carrelage mural blanc brillant 30x60 - m²", "Carrelage", 16.90,
           "m2", description="Faïence murale blanche 30x60cm, finition brillante, intérieur",
           subcategory="Carrelage mural"),
        _p("Carrelage mural metro blanc 10x20 biseauté - m²", "Carrelage", 24.90,
           "m2", description="Carrelage métro blanc biseauté 10x20cm, style industriel",
           subcategory="Carrelage mural"),
        _p("Carrelage imitation parquet chêne 20x120 - m²", "Carrelage", 34.90,
           "m2", description="Carrelage grès cérame imitation bois chêne naturel, 20x120cm",
           subcategory="Carrelage sol"),
        _p("Mortier colle flexible C2 gris - sac 25kg", "Carrelage", 14.90,
           "sac 25kg", description="Colle carrelage C2TE grande surface, flexible, intérieur/extérieur",
           subcategory="Colles & joints"),
        _p("Mortier colle blanc C1 - sac 25kg", "Carrelage", 11.90,
           "sac 25kg", description="Colle carrelage C1 standard, blanc, pour carrelage mural intérieur",
           subcategory="Colles & joints"),
        _p("Joint carrelage sableuse gris perle - sac 5kg", "Carrelage", 12.50,
           "sac 5kg", description="Joint de carrelage sableux gris perle, joints de 2 à 10mm",
           subcategory="Colles & joints"),
        _p("Joint époxy carrelage blanc - kit 2kg", "Carrelage", 28.90,
           "kit", description="Joint époxy bicomposant blanc, résistant aux acides, sanitaire",
           subcategory="Colles & joints"),
        _p("Primaire d'accrochage pour carrelage 5L", "Carrelage", 19.90,
           "bidon 5L", description="Primaire sol et mur pour améliorer l'adhérence du mortier colle",
           subcategory="Colles & joints"),
        _p("Croisillons carrelage 3mm (sachet 500)", "Carrelage", 4.90,
           "sachet", description="Croisillons en T pour espacement régulier des carreaux",
           subcategory="Accessoires"),
        _p("Truelle dentelée 6x6mm manche bois", "Carrelage", 12.90,
           description="Truelle à denture carrée 6x6mm pour pose de carrelage",
           subcategory="Outils"),
        _p("Découpe carrelage électrique 600W lame 115mm", "Carrelage", 89.90,
           description="Carrelette électrique avec plateau, lame diamant 115mm",
           subcategory="Outils"),

        # ── Menuiserie ───────────────────────────────────────────────────────
        _p("Panneau OSB 3 18mm 250x125cm", "Menuiserie", 29.90,
           description="Panneau OSB 3 humidité, 18mm, 250x125cm, pour plancher et mur porteur",
           subcategory="Panneaux"),
        _p("Panneau MDF 16mm 250x125cm", "Menuiserie", 34.90,
           description="Panneau MDF E1 16mm, 250x125cm, deux faces lisses, menuiserie intérieure",
           subcategory="Panneaux"),
        _p("Planche pin massif raboté 200x28mm - barre 2.4m", "Menuiserie", 18.90,
           "barre", description="Planche pin sylvestre raboté 200x28mm, traité classe 2",
           subcategory="Bois massif"),
        _p("Porte intérieure ISO plane blanc - 83x204cm", "Menuiserie", 89.90,
           description="Porte intérieure isoplane peinte blanc, 83x204cm, âme alvéolaire",
           subcategory="Portes"),
        _p("Porte intérieure ISO plâne chêne - 73x204cm", "Menuiserie", 129.00,
           description="Porte intérieure finition chêne clair, 73x204cm, précoupée",
           subcategory="Portes"),
        _p("Paumelle charnière réglable 3D - paire", "Menuiserie", 24.90,
           "paire", description="Paumelle réglable 3 axes pour porte intérieure, finition chromée",
           subcategory="Quincaillerie"),
        _p("Poignée de porte sur plaque inox brossé", "Menuiserie", 29.90,
           "paire", description="Poignée de porte avec plaque, condamnation WC, inox brossé",
           subcategory="Quincaillerie"),
        _p("Parquet flottant chêne 12mm - paquet 1.8m²", "Menuiserie", 49.90,
           "paquet", description="Parquet flottant stratifié chêne naturel 12mm, clipsable AC5",
           subcategory="Parquet"),
        _p("Sous-couche parquet acoustique 2mm - rouleau 15m²", "Menuiserie", 19.90,
           "rouleau", description="Sous-couche mousse PE + film hydrofuge pour parquet flottant",
           subcategory="Parquet"),
        _p("Plinthe MDF prépeinte 66mm - barre 2.4m", "Menuiserie", 7.90,
           "barre", description="Plinthe rodapié MDF prépeinte blanc, profil arrondi, 66x10mm",
           subcategory="Plinthes"),
        _p("Moulure de jonction parquet 2.4m", "Menuiserie", 12.90,
           "barre", description="Barre de seuil de jonction pour parquet et carrelage, alu anodisé",
           subcategory="Parquet"),
        _p("Vis à bois 4x40mm boîte 200", "Menuiserie", 6.90,
           "boîte 200", description="Vis bois tête fraisée pozidriv 4x40mm, acier zingué",
           subcategory="Quincaillerie"),
        _p("Chevron épicéa raboté 50x75mm - barre 3m", "Menuiserie", 14.90,
           "barre", description="Chevron résineux épicéa raboté 4 faces, 50x75mm, classe 1",
           subcategory="Bois massif"),
    ]
